name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: garyhtou
          template: classic
          base: header, activity, community, repositories
          repositories: 1000
          config_timezone: America/Los_Angeles
          config_display: columns
          config_order: base, languages, wakatime, habits

          plugin_lines: yes

          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200

          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: true
          plugin_languages_analysis_timeout: 30

          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages-graphs, editors-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

