name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: garyhtou
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          repositories: 1000
          repositories_affiliations: owner
          config_timezone: America/Los_Angeles
          config_order: base.header, base.activity+community, base.repositories, wakatime, languages, notable, habits

          plugin_lines: yes
          plugin_notable: yes
          plugin_traffic: yes

          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 500

          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: hackclub/bank
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 0

          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages, os, languages-graphs, editors-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

